Jironimo.Web/Areas/Admin/Controllers/DeveloperController.cs
using AutoMapper;
using Jironimo.Common.Abstract.Services;
using Jironimo.Common.Models.Developers;
using Jironimo.Web.Areas.Admin.Models.Developers;
using Microsoft.AspNetCore.Mvc;

namespace Jironimo.Web.Areas.Admin.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly IDeveloperService _developerService;
        private readonly IImageUploadService _imageUploadService;
        private readonly IMapper _mapper;

        public DeveloperController(IDeveloperService developerService, IMapper mapper, IImageUploadService imageUploadService)
        {
            _developerService = developerService;
            _mapper = mapper;
            _imageUploadService = imageUploadService;
        }

        public ActionResult Index()
        {
            ViewBag.Developers= _developerService.GetDevelopers();
            return View("~/Areas/Admin/Views/Developer/Developer.cshtml");
        }

        [HttpPost]
        public async Task<ActionResult> Create(DeveloperCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newDeveloper = _mapper.Map<Developer>(model);
                newDeveloper.ImagePath = await _imageUploadService.UploadImage(model.ImagePath, "/images/Developers/");

                try
                {
                    var application = _mapper.Map<Developer>(newDeveloper);
                    _developerService.Create(application);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewBag.Developers = _developerService.GetDevelopers();
            return View("~/Areas/Admin/Views/Developer/Developer.cshtml", model);
        }

        public ActionResult Delete(Guid id)
        {
            var applicationDetails = _developerService.GetById(id);
            _imageUploadService.DeleteImage(applicationDetails.ImagePath, "/images/Developers/");
            _developerService.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Jironimo.Web/Controllers/API/CategoryController.cs
using AutoMapper;
using Jironimo.Common.Abstract.Services;
using Jironimo.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Jironimo.Web.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public CategoryController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var categories = _mapper.Map<List<CategoryViewModel>>(_categoryService.GetCategories());
            return Json(categories);
        }
    }     
}

Jironimo.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="~/css/admin/styles.css" rel="stylesheet" />
    <link type="image/png" sizes="32x32" href="/icons/logo.png" />
    <title>@ViewData["Title"] - Jironimo.Web</title>
    @RenderSection("Styles", false)
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="/">Applage</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <a class="btn btn-primary" href="/logout" type="button">Logout</a>
            </div>
        </div>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" asp-controller="Category" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Category
                        </a>
                        <a class="nav-link" asp-controller="Application" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Application
                        </a>
                        <a class="nav-link" asp-controller="ApplicationDetails" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Application Details
                        </a>
                        <a class="nav-link" asp-controller="Developer" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Developer
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">© Jironimo 2022 — Ukraine</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @RenderSection("Scripts", required: false)
    <script src="~/js/admin.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Jironimo.Web/Areas/Admin/Views/Shared/_LayoutEmpty.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>@ViewData["Title"] - Jironimo.Web</title>
    @RenderSection("Styles", false)
</head>
<body>
    @RenderBody()
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>